# Generated by Django 4.1.3 on 2022-11-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feed_number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user',
            name='follower_number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user',
            name='following_number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_text',
            field=models.TextField(default=' '),
        ),
    ]
