# Generated by Django 4.1.3 on 2022-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_feed_number_user_follower_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.TextField(default="/media/default_profile_photo.png"),
        ),
    ]
