# Generated by Django 4.1.3 on 2022-11-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_user_feed_number_user_follower_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='feed_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follower_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_text',
        ),
    ]
