# Generated by Django 4.1.3 on 2023-01-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0004_remove_user_feed_number_remove_user_follower_number_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="profile_image",
        ),
    ]
